### ISSUE TITLE
Ajouter un menu déroulant Qui-suis-je ?

### ISSUE THREAD

**Issue by johnkrovitch** [johnkrovitch/LeComptoirDeLEcureuil#31]
Qui suis-je ?
-> Présentation
-> Parcours
-> Réalisations

**Comment by johnkrovitch** [comment]
@Salveena il ne te reste plus qu'à remplir les pages :)

**Comment by Salveena** [comment]
Demain oui :-)
Ce serait bien je boucle mon site.

Le 6 oct. 2016 11:26 PM, "Arnaud Frézet" <notifications@github.com> a
écrit :
