### ISSUE TITLE
Prévisualiser un article ne fonctionne pas correctement

### ISSUE THREAD

**Issue by johnkrovitch** [johnkrovitch/LeComptoirDeLEcureuil#38]
N'est pas en synchro avec le tinyMce et avec l'affichage de l'article

**Comment by johnkrovitch** [comment]
@Salveena cela fonctionne-t-il correctement maintenant ?

**Comment by Salveena** [comment]
http://lecomptoirdelecureuil.fr/2016/10/eos-exils-g-d-arthur

J'ai fait un test avec le dernier article en cours EOS tome 2 et j'ai
encore "Cette noisette n'est vraiment pas bonne... Peut être en
cherchiez-vous une autre ?"
J'ai rechargé la page mais idem.

2016-10-11 19:00 GMT+02:00 Arnaud Frézet <notifications@github.com>:

**Comment by johnkrovitch** [comment]
@Salveena cela fonctionne-t'il maintenant ?

**Comment by Salveena** [comment]
ça fonctionne ! :)
