### ISSUE TITLE
Partenaires

### ISSUE THREAD

**Issue by Salveena** [johnkrovitch/LeComptoirDeLEcureuil#42]
J'aimerais ajouter un nouveau partenaire : Editions Rivière Blanche

Et aussi hiérarchiser ceux existant, si c'est possible.

Enfin, j'ai supprimé La Bourdonnaye, mais il apparaît toujours en ligne.

Et encore une chose, j'aimerais mettre les twitters, instagram et fb des partenaires via une icone. Est-ce possible ? :)

**Comment by johnkrovitch** [comment]
fixed
