### ISSUE TITLE
Sites à noisettes

### ISSUE THREAD

**Issue by Salveena** [johnkrovitch/LeComptoirDeLEcureuil#43]
Je vais simplement remettre un lien vers mes partenaires
- Esa-Digital http://esadigitalgame.com/
- Editions ActuSf http://www.editions-actusf.fr/
- Editions Mnémos http://www.mnemos.com/
- Editions du Chat Noir http://www.editionsduchatnoir.fr/
- Editions Rivière Blanche http://www.riviereblanche.com/
- Librairie L'Esprit Livre http://www.lesprit-livre.fr/
- Librairie Trollune http://www.trollune.fr/
- Le Dépôt Imaginaire http://ledepotimaginaire.fr/

**Comment by johnkrovitch** [comment]
Done

**Comment by Salveena** [comment]
<3

2016-10-11 19:24 GMT+02:00 Arnaud Frézet <notifications@github.com>:
