### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Salveena** [johnkrovitch/LeComptoirDeLEcureuil#44]
Euh... mes articles affichent tous la date d'aujourd'hui 😮 c'est à dire 07/10/2016 sur la page principale, dans les catégories c'est bon.

Et truc bizarre les 5 derniers articles n'apparaissent pas dans leurs catégories mais seulement sur la page principale... (A noter, ce sont qui n'ont pas été importé et que j'ai recréé)

**Comment by johnkrovitch** [comment]
Fixed
