### ISSUE TITLE
Ajouter un moteur de recherche pour les articles

### ISSUE THREAD

**Issue by johnkrovitch** [johnkrovitch/LeComptoirDeLEcureuil#60]
{#<form class="navbar-form navbar-right" role="search">#}
    {#<div class="form-group">#}
    {#<input type="text" class="form-control" placeholder="{{ 'lecomptoir.menu.search' | trans }}">#}
    {#</div>#}
    {#<button type="submit" class="btn hvr-bounce-in"><i class="fa fa-search"></i></button>#}
    {#</form>#}

**Comment by johnkrovitch** [comment]
@Salveena à valider sur staging

**Comment by Salveena** [comment]
ça marche pas mal a priori. :)
