### ISSUE TITLE
Créer une rubrique "brèves de comptoir" à la place de "sites à noisettes"

### ISSUE THREAD

**Issue by Salveena** [johnkrovitch/LeComptoirDeLEcureuil#61]
Les articles seront créés sous la catégorie "Brèves de Comptoir" et seront court.
La rubrique afficherait les gros titres des 3 derniers articles.

**Comment by johnkrovitch** [comment]
@Salveena à valider sur staging

**Comment by Salveena** [comment]
Cette noisette n'est vraiment pas bonne !
Au moment de sauvegarder un article dans la catégorie "brèves", j'ai eu ce message.

**Comment by johnkrovitch** [comment]
fixed
