### ISSUE TITLE
telechargement des images ne fonctionne pas sur le site test du Comptoir

### ISSUE THREAD

**Issue by Salveena** [johnkrovitch/LeComptoirDeLEcureuil#67]
Voilà, j'ai fait le test d'ajouter une image avec le bouton "ajouter une galerie d'image".
La pop up pour "Uploader une média" s'affiche et je peux chercher l'image dans les dossiers sans soucis. 
Par contre quand je mets "ouvrir" (double clic) le document, il ne se passe rien. Aucun téléchargement.

**Comment by johnkrovitch** [comment]
@Salveena à valider sur staging

**Comment by Salveena** [comment]
c'est bon
