### ISSUE TITLE
La clé captcha ne fonctionne pas

### ISSUE THREAD

**Issue by Salveena** [johnkrovitch/LeComptoirDeLEcureuil#68]
Lorsque je teste les commentaires, la clé captcha m'affiche : "ERREUR pour le propriétaire du site : Clé de site non valide"
ou " Le captcha est invalide. Pouvez-vous réessayer ?"
Pourtant je suis déconnectée du site et j'ai rechargé la page et j'ai entré ton adresse mail.

Et si le captcha ne fonctionne pas, le commentaire ne s'affiche pas.

**Comment by johnkrovitch** [comment]
fixed
